# Generated by Django 5.2.1 on 2025-06-14 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceuil', '0015_remove_commentaire_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('NCI', models.CharField(max_length=255, unique=True)),
                ('poste', models.CharField(max_length=255)),
                ('contacts_1', models.CharField(max_length=255)),
                ('contacts_2', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile Client',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('contenue', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
