# Generated by Django 5.2.1 on 2025-06-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contacts_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contacts_2',
        ),
        migrations.AlterField(
            model_name='client',
            name='poste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('type_contact', models.CharField(choices=[('EMAIL', 'Email'), ('TEL', 'Téléphone'), ('MOBILE', 'Mobile'), ('FAX', 'Fax')], max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
