# Generated by Django 5.2.1 on 2025-06-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_nci_alter_client_date_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
