# Generated by Django 5.2.1 on 2025-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_dashboardclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_client/'),
        ),
    ]
