# Generated by Django 5.2.1 on 2025-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardclient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/', verbose_name='Photo de profile client par default'),
        ),
    ]
