# Generated by Django 5.2.1 on 2025-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_dashboardclient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
