# Generated by Django 5.2.1 on 2025-06-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_localisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='NCI',
            new_name='CNI',
        ),
    ]
