# Generated by Django 5.2.1 on 2025-06-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_rename_nci_client_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
