# Generated by Django 5.2.1 on 2025-06-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_client_contact1_client_contact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='profile_client/default.png', null=True, upload_to='profile_client/'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
