# Generated by Django 5.2.1 on 2025-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_panier_souscription_versement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='ajouter_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
