# Generated by Django 5.2.1 on 2025-06-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_commentaire_ajouter_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='ajouter_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
