# Generated by Django 5.2.1 on 2025-06-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristiqueProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('description', models.CharField(max_length=190)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('description', models.CharField(max_length=190)),
                ('image', models.ImageField(upload_to='plan_projet/')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=200)),
                ('contenue', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('montant_investissement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalite_investissement', models.CharField(choices=[('Jour', 'JOUR'), ('Semaine', 'SEMAINE'), ('Mois', 'MOIS'), ('Année', 'ANNEE')], max_length=100)),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(upload_to='projet')),
                ('slug', models.SlugField(unique=True)),
                ('localisation', models.CharField(blank=True, max_length=190, null=True)),
                ('option', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('titre', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(upload_to='album')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaracteristiquePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
