# Generated by Django 5.2.1 on 2025-06-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceuil', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client_projet',
            field=models.ManyToManyField(through='client.Souscription', to='client.client'),
        ),
        migrations.AddField(
            model_name='plan',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet'),
        ),
        migrations.AddField(
            model_name='phase',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet'),
        ),
        migrations.AddField(
            model_name='caracteristiqueprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet'),
        ),
    ]
