# Generated by Django 5.2.1 on 2025-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='cout',
            new_name='cout_total',
        ),
        migrations.AddField(
            model_name='projet',
            name='montant_investissement',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
    ]
