# Generated by Django 5.2.1 on 2025-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_rename_cout_projet_cout_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
