# Generated by Django 5.2.1 on 2025-06-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0003_projet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='modalite_investissement',
            field=models.CharField(choices=[('jour', 'JOUR'), ('semaine', 'SEMAINE'), ('mois', 'MOIS'), ('annee', 'ANNEE')], default='MOIS'),
            preserve_default=False,
        ),
    ]
