# Generated by Django 5.2.1 on 2025-06-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_projet_modalite_investissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
