# Generated by Django 5.2.1 on 2025-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0007_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='poste',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
