# Generated by Django 5.2.1 on 2025-06-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0009_projet_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='libelle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projet',
            name='slug',
            field=models.SlugField(default='projet', unique=True),
            preserve_default=False,
        ),
    ]
