# Generated by Django 5.2.1 on 2025-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0010_alter_projet_libelle_alter_projet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='option',
            field=models.CharField(default='En vedette', max_length=100),
            preserve_default=False,
        ),
    ]
