# Generated by Django 5.2.1 on 2025-06-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0011_projet_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerieVette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='projet_slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderVette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='projet_slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
