# Generated by Django 5.2.1 on 2025-06-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0012_galerievette_slidervette'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(default='img', upload_to='plan_projet/'),
            preserve_default=False,
        ),
    ]
