# Generated by Django 5.2.1 on 2025-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0013_plan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
