# Generated by Django 5.2.1 on 2025-06-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0014_plan_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='client',
        ),
    ]
