# Generated by Django 5.2.1 on 2025-06-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0015_remove_commentaire_client'),
        ('client', '0001_initial'),
        ('general', '0044_alter_commentairevedette_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='projet',
        ),
        migrations.AlterField(
            model_name='projet',
            name='client_projet',
            field=models.ManyToManyField(through='acceuil.Souscription', to='client.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
