# Generated by Django 5.2.1 on 2025-06-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0016_alter_souscription_client_alter_versement_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscription',
            name='client',
        ),
        migrations.RemoveField(
            model_name='souscription',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='projet',
        ),
    ]
