# Generated by Django 5.2.1 on 2025-06-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0017_remove_souscription_client_and_more'),
        ('client', '0012_panier_souscription_versement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='client_projet',
            field=models.ManyToManyField(through='client.Souscription', to='client.client'),
        ),
        migrations.DeleteModel(
            name='Souscription',
        ),
        migrations.DeleteModel(
            name='Versement',
        ),
    ]
