# Generated by Django 5.2.1 on 2025-06-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0018_alter_projet_client_projet_delete_souscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidervette',
            name='projet',
        ),
        migrations.DeleteModel(
            name='GalerieVette',
        ),
        migrations.DeleteModel(
            name='SliderVette',
        ),
    ]
