# Generated by Django 5.2.1 on 2025-06-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0019_remove_slidervette_projet_delete_galerievette_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='modalite_investissement',
            field=models.CharField(choices=[('jour', 'JOUR'), ('semaine', 'SEMAINE'), ('mois', 'MOIS'), ('annee', 'ANNEE')], max_length=100),
        ),
    ]
