# Generated by Django 5.2.1 on 2025-06-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0020_alter_projet_modalite_investissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='modalite_investissement',
            field=models.CharField(choices=[('Jour', 'JOUR'), ('Semaine', 'SEMAINE'), ('Mois', 'MOIS'), ('Année', 'ANNEE')], max_length=100),
        ),
    ]
