# Generated by Django 5.2.1 on 2025-06-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceuil', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartementsVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appropos/')),
                ('presentation', models.TextField()),
                ('slogan', models.CharField(max_length=190)),
                ('option', models.CharField(max_length=190)),
                ('route', models.CharField(blank=True, max_length=190, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('denomination', models.CharField(max_length=190)),
                ('image', models.ImageField(upload_to='compagnie/')),
                ('description', models.CharField(max_length=190)),
                ('localisation', models.CharField(max_length=190)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('flaticon-select', 'Projet'), ('flaticon-office', 'Logement'), ('flaticon-excavator', 'Construction'), ('flaticon-armchair', 'Propriete')], max_length=100)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('valeur', models.PositiveIntegerField()),
                ('intitule_valeur', models.CharField(blank=True, max_length=10, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('section_title', models.CharField(choices=[('presentation', 'Presentation'), ('compagnie', 'Compagnie'), ('services', 'Services'), ('espace_client', 'Espace Client'), ('mail', 'Ecrivez nous')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('lien_title', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('nom', models.CharField(max_length=190)),
                ('prenom', models.CharField(max_length=190)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('poste', models.CharField(blank=True, max_length=190, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('route', models.CharField(choices=[('acceuil', 'Acceuil'), ('service', 'Service'), ('appropos', 'Appropos'), ('projets', 'Projets')], max_length=190)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolitiqueConfidentialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('contenue', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('active_libelle', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApproposPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('intitule', models.CharField(max_length=190)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appropos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaracteristiqueVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaireVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commentaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appropos',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(choices=[('icon-call', 'Telephone')], max_length=100)),
                ('libelle', models.CharField(max_length=190)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('router', models.CharField(blank=True, max_length=190, null=True)),
                ('description_email', models.CharField(blank=True, max_length=190, null=True)),
                ('mode_payement', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='general.footer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalerieVette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(upload_to='projet_slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAppVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_app_vedette/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageFareVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_app_vedette/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(choices=[('flaticon-home-2', 'Propriete Intelligent'), ('flaticon-mountain', 'Travaux Public'), ('flaticon-heart', 'Propriete Saine'), ('flaticon-secure', 'Securite')], max_length=100)),
                ('libelle', models.CharField(max_length=190)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appropos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjetTerminer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('option', models.CharField(max_length=100)),
                ('date_de_fin', models.DateField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReseauxSociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')], max_length=100)),
                ('url', models.TextField()),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReseauxSociauxStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')], max_length=100)),
                ('url', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.membrestaff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('libelle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=190)),
                ('option', models.CharField(blank=True, max_length=190, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='services_detail/')),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('contenue', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.servicecard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appropos/')),
                ('contenue', models.TextField()),
                ('option', models.CharField(max_length=190)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=190)),
                ('intitule', models.CharField(max_length=190)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.servicesection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SliderVette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=190, null=True)),
                ('description', models.CharField(blank=True, max_length=190, null=True)),
                ('image', models.ImageField(upload_to='projet_slider')),
                ('order', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
