# Generated by Django 5.2.1 on 2025-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planvedette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_vedette_home/'),
        ),
    ]
