# Generated by Django 5.2.1 on 2025-05-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='descripton_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='mode_payement',
            field=models.ImageField(blank=True, null=True, upload_to='footer/'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='router',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
