# Generated by Django 5.2.1 on 2025-05-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_footersection_descripton_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footersection',
            old_name='descripton_email',
            new_name='description_email',
        ),
    ]
