# Generated by Django 5.2.1 on 2025-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_descripton_email_footersection_description_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='reseaux_sociaux',
            field=models.BooleanField(default=0),
        ),
    ]
