# Generated by Django 5.2.1 on 2025-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_compagnie_reseaux_sociaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='lien_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
