# Generated by Django 5.2.1 on 2025-05-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_footer_description_footer_libelle_footer_lien_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='section',
            new_name='section_title',
        ),
    ]
