# Generated by Django 5.2.1 on 2025-05-31 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_rename_section_footer_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_title', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='footer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='lien_title',
        ),
        migrations.AlterField(
            model_name='footersection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='general.footer'),
        ),
    ]
