# Generated by Django 5.2.1 on 2025-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_footerside_remove_footer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
