# Generated by Django 5.2.1 on 2025-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
