# Generated by Django 5.2.1 on 2025-06-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_slide_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='denomination',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
