# Generated by Django 5.2.1 on 2025-06-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_compagnie_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='slogan',
            field=models.CharField(default='Notre objectif vous rendre proprietaire', max_length=255),
            preserve_default=False,
        ),
    ]
