# Generated by Django 5.2.1 on 2025-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_compagnie_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('projet', 'Projet'), ('logement', 'Logement'), ('construction', 'Construction'), ('propriete', 'Propriete')])),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('valeur', models.PositiveIntegerField()),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
