# Generated by Django 5.2.1 on 2025-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_compteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='intitule_valeur',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='type',
            field=models.CharField(choices=[('flaticon-select', 'Projet'), ('flaticon-office', 'Logement'), ('flaticon-excavator', 'Construction'), ('flaticon-armchair', 'Propriete')]),
        ),
    ]
