# Generated by Django 5.2.1 on 2025-06-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_compteur_intitule_valeur_alter_compteur_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartementsVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaracteristiqueVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAppVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_app_vedette/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageFareVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_app_vedette/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appartementsvedette')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
