# Generated by Django 5.2.1 on 2025-06-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0007_commentaire'),
        ('general', '0017_planvedette'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireVedette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.commentaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
