# Generated by Django 5.2.1 on 2025-06-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0008_client_poste'),
        ('general', '0018_commentairevedette'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetTermine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('date_de_fin', models.DateField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceuil.projet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
