# Generated by Django 5.2.1 on 2025-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0008_client_poste'),
        ('general', '0019_projettermine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjetTermine',
            new_name='ProjetTerminer',
        ),
    ]
