# Generated by Django 5.2.1 on 2025-06-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_rename_projettermine_projetterminer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(choices=[('flaticon-home-2', 'Propriete Intelligent'), ('flaticon-mountain', 'Travaux Public'), ('flaticon-heart', 'Propriete Saine'), ('flaticon-secure', 'Securite')])),
                ('libelle', models.CharField(max_length=255)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
