# Generated by Django 5.2.1 on 2025-06-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='image_representation',
            field=models.ImageField(blank=True, null=True, upload_to='compagnie/'),
        ),
    ]
