# Generated by Django 5.2.1 on 2025-06-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_compagnie_image_representation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compagnie',
            old_name='image_representation',
            new_name='image_appropos',
        ),
    ]
