# Generated by Django 5.2.1 on 2025-06-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_rename_image_representation_compagnie_image_appropos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compagnie',
            name='Contact_1',
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='Contact_2',
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='image_appropos',
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='reseaux_sociaux',
        ),
        migrations.RemoveField(
            model_name='compagnie',
            name='slogan',
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Appropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('denomination', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appropos/')),
                ('presentation', models.TextField()),
                ('slogan', models.CharField(max_length=255)),
                ('option', models.CharField(max_length=255)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='prestation',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appropos'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(verbose_name=[('icon-call', 'Telephone')])),
                ('libelle', models.CharField(max_length=255)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReseauxSociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('icon', models.CharField(verbose_name=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Whatsapp'), ('fab fa-whatsapp', 'Gmail')])),
                ('url', models.TextField()),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.compagnie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
