# Generated by Django 5.2.1 on 2025-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_remove_compagnie_contact_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(choices=[('icon-call', 'Telephone')]),
        ),
        migrations.AlterField(
            model_name='reseauxsociaux',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Whatsapp'), ('fab fa-whatsapp', 'Gmail')]),
        ),
    ]
