# Generated by Django 5.2.1 on 2025-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_alter_contact_icon_alter_reseauxsociaux_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appropos',
            name='denomination',
        ),
        migrations.AddField(
            model_name='compagnie',
            name='denomination',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
