# Generated by Django 5.2.1 on 2025-06-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_remove_appropos_denomination_compagnie_denomination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compagnie',
            old_name='localistation',
            new_name='localisation',
        ),
    ]
