# Generated by Django 5.2.1 on 2025-06-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_rename_localistation_compagnie_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ordre',
        ),
        migrations.AddField(
            model_name='service',
            name='compagnie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.compagnie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='contenue',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appropos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='option',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
