# Generated by Django 5.2.1 on 2025-06-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_remove_service_description_remove_service_ordre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesection',
            old_name='intitule',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='service',
            name='compagnie',
        ),
        migrations.RemoveField(
            model_name='service',
            name='contenue',
        ),
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='compagnie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.compagnie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesection',
            name='contenue',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appropos/'),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ServiceSectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.servicesection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
