# Generated by Django 5.2.1 on 2025-06-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_rename_intitule_servicesection_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='compagnie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.compagnie'),
            preserve_default=False,
        ),
    ]
