# Generated by Django 5.2.1 on 2025-06-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_service_compagnie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceCard',
        ),
    ]
