# Generated by Django 5.2.1 on 2025-06-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_rename_service_servicecard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='route',
        ),
    ]
