# Generated by Django 5.2.1 on 2025-06-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_remove_servicesection_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproposPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.appropos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
