# Generated by Django 5.2.1 on 2025-06-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_membrestaff_reseauxsociauxstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrestaff',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
