# Generated by Django 5.2.1 on 2025-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_membrestaff_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrestaff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
