# Generated by Django 5.2.1 on 2025-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_membrestaff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseauxsociaux',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')]),
        ),
        migrations.AlterField(
            model_name='reseauxsociauxstaff',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')]),
        ),
    ]
