# Generated by Django 5.2.1 on 2025-06-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_servicedetail_servicepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
