# Generated by Django 5.2.1 on 2025-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_delete_servicepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecard',
            name='route',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='libelle',
            field=models.CharField(max_length=200),
        ),
    ]
