# Generated by Django 5.2.1 on 2025-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0040_remove_servicecard_route_servicecard_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecard',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
