# Generated by Django 5.2.1 on 2025-06-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0041_alter_servicecard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='image',
            field=models.ImageField(default=1, upload_to='services_detail/'),
            preserve_default=False,
        ),
    ]
