# Generated by Django 5.2.1 on 2025-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0042_alter_servicedetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetterminer',
            name='option',
            field=models.CharField(default='Terminer', max_length=100),
            preserve_default=False,
        ),
    ]
