# Generated by Django 5.2.1 on 2025-06-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('general', '0043_projetterminer_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairevedette',
            name='commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.commentaire'),
        ),
    ]
