# Generated by Django 5.2.1 on 2025-06-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0044_alter_commentairevedette_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='route',
            field=models.CharField(choices=[('acceuil', 'Acceuil'), ('service', 'Service'), ('appropos', 'Appropos'), ('projet', 'Projet')], default='acceuil', max_length=255),
            preserve_default=False,
        ),
    ]
