# Generated by Django 5.2.1 on 2025-06-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0045_menu_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='route',
            field=models.CharField(choices=[('acceuil', 'Acceuil'), ('service', 'Service'), ('appropos', 'Appropos'), ('projets', 'Projets')], max_length=255),
        ),
    ]
