# Generated by Django 5.2.1 on 2025-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_alter_menu_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiqueConfidentialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajouter_le', models.DateField(auto_now_add=True)),
                ('modifie_le', models.DateField(auto_now=True)),
                ('libelle', models.CharField(max_length=255)),
                ('contenue', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
