# Generated by Django 5.2.1 on 2025-06-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_politiqueconfidentialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='politiqueconfidentialite',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politiqueconfidentialite',
            name='libelle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
