# Generated by Django 5.2.1 on 2025-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0049_slide_description_galerievette_slidervette'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidervette',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
