# Generated by Django 5.2.1 on 2025-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0050_slidervette_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active_libelle',
            field=models.BooleanField(default=1),
        ),
    ]
