# Generated by Django 5.2.1 on 2025-06-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0051_slide_active_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='libelle',
            field=models.CharField(default='Presentation', max_length=255),
            preserve_default=False,
        ),
    ]
