# Generated by Django 5.2.1 on 2025-06-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0052_footer_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='type',
            field=models.CharField(choices=[('flaticon-select', 'Projet'), ('flaticon-office', 'Logement'), ('flaticon-excavator', 'Construction'), ('flaticon-armchair', 'Propriete')], max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='section_title',
            field=models.CharField(choices=[('presentation', 'Presentation'), ('compagnie', 'Compagnie'), ('services', 'Services'), ('espace_client', 'Espace Client'), ('mail', 'Ecrivez nous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reseauxsociauxstaff',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')], max_length=100),
        ),
    ]
