# Generated by Django 5.2.1 on 2025-06-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0053_alter_compteur_type_alter_footer_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(choices=[('icon-call', 'Telephone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='icon',
            field=models.CharField(choices=[('flaticon-home-2', 'Propriete Intelligent'), ('flaticon-mountain', 'Travaux Public'), ('flaticon-heart', 'Propriete Saine'), ('flaticon-secure', 'Securite')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reseauxsociaux',
            name='icon',
            field=models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google', 'Gmail'), ('fab fa-whatsapp', 'Whatsapp')], max_length=100),
        ),
    ]
